export const StringResource = {
  ko: {
    welcome: "환영합니다!",
    login: "로그인",
    kakao_login: "카카오로 시작하기",
    apple_login: "Apple로 시작하기",
    email_login: "이메일로 시작하기",
    google_login: 'Google로 시작하기',
    email: "이메일",
    password: "비밀번호",
    input_email_message: "이메일을 입력해주세요",
    input_password_message: "비밀번호를 입력해주세요",
    not_member_sign_up: "아직 회원이 아니신가요?",
    create_account: "회원가입하기",
    do_start: "시작하기",
    sign_up: "가입하기",
    required: "필수",
    email_format: "이메일 주소 형식",
    password_min_length: "8자리 이상",
    password_requirements: "영문 / 숫자 / 특수문자 혼용",
    next: "다음으로",
    fail_login: '로그인 실패',
    fail_sign_up: '회원가입 실패',
    unknown_error_message: '알 수 없는 에러가 발생했습니다',
    onboarding_profile: '프로필 설정',
    onboarding_favorite_studio: '관심 스튜디오',
    onboarding_agreement: '개인정보 동의',
    change_profile_message: '프로필을 설정해주세요!',
    change_profile_description: '언제든 변경할 수 있어요. 나만의 닉네임을 지어보세요.',
    follow_studio_message: '관심 학원을 팔로우해요',
    follow_studio_description: '어떤 스튜디오에 관심있으십니까?',
    agreement_message: '서비스를 위해 동의해주세요!',
    all_agreement: '모두 동의하기',
    service_terms_agreement_required: '[필수] 서비스 이용약관',
    service_privacy_agreement_required: '[필수] 개인정보 수집 및 이용동의',
    service_terms_agreement: '서비스 이용약관',
    service_privacy_agreement: '개인정보 수집 및 이용동의',
    nick_name: '닉네임',
    welcome_title: '환영합니다! 🎉',
    welcome_message: 'Rawgraphy와 함께 멋진 순간을 만들어봐요.',
    duplicate_nick_name_message: '이미 사용중인 닉네임입니다',
    popular_studio: '인기 스튜디오',
    popular_lesson: '인기 수업',
    studio: '스튜디오',
    more: '더보기',
    following: '팔로잉',
    follow: '팔로우',
    ticket: '레슨 수강권',
    payment_records: '구매내역',
    terms_and_policy: '약관 및 정책',
    inquiry: '문의하기',
    log_out_success_message: '성공적으로 로그아웃하였습니다.',
    log_out_dialog_message: '정말로 로그아웃 하시겠습니까?',
    log_out: '로그아웃',
    rawgraphy: 'Rawgraphy',
    under_development_message: '개발 중인 메뉴입니다. 조금만 기다려주세요!',
    sign_out: '회원탈퇴',
    account: '계정',
    payment: '결제하기',
    app_version: '앱버전',
    confirm: '확인',
    edit_profile: '프로필 수정',
    notification: '알림',
    notification_setting: '알림 설정',
    upcoming_lessons: '다가오는 수업',
    sign_out_reason_no_contents: '원하는 콘텐츠가 부족해요.',
    sign_out_reason_no_use: '앱을 자주 사용하지 않아요.',
    sign_out_reason_error: '이용 중 오류가 자주 발생해요.',
    sign_out_reason_new_account: '새 계정을 만들고 싶어요.',
    sign_out_title: '정말 탈퇴하시겠어요? 😢',
    sign_out_description: '회원님이 떠나신다니 너무 아쉬워요.\n탈퇴하시면 계정 정보와 활동 내역이 삭제되며, 한 달 이전에는 복구가 가능해요.',
    sign_out_reason_question: '탈퇴하시려는 이유가 무엇인지 궁금해요.',
    sign_out_dialog_message: '정말로 회원탈퇴 하시겠습니까?\n회원님의 데이터가 모두 삭제됩니다.',
    guitar: '기타',
    continue_use: '계속 이용하기',
    do_sign_out: '네, 탈퇴할게요',
    sign_out_reason_placeholder: '어떤 점이 불편하셨나요? 더 좋은 서비스가 될 수 있도록 의견을 남겨주세요!',
    maintenance_title: '서버 점검 중입니다',
    maintenance_description: '더 나은 서비스를 위해 시스템 점검 중입니다.',
    maintenance_try_later: '잠시 후 다시 이용해 주시기 바랍니다.',
    maintenance_time: '예상 점검 시간: 22:00 ~ 02:00',
    empty_notification_title: '새로운 소식이 없어요',
    empty_notification_description: '알림이 오면 여기서 확인할 수 있어요',
    invalid_date_format: '잘못된 날짜',
    days_ago: '{n}일 전',
    hours_ago: '{n}시간 전',
    minutes_ago: '{n}분 전',
    minutes: '분',
    just_now: '방금 전',
    my_ticket: '내 수강권 보러가기',
    purchase_ticket: '수강권 결제하기',
    finish_lesson_title: '종료된 수업입니다',
    date: '날짜',
    day: '요일',
    mon: '월',
    tue: '화',
    wed: '수',
    thu: '목',
    fri: '금',
    sat: '토',
    sun: '일',
    unknown: '',
    finish: '종료',
    start: '시작',
    won: '원',
    lesson_duration: '수업시간',
    lesson_room: '강의실',
    bank_transfer_message: '아래 계좌로 입금해 주시면 확인 후 구매 결정해드리겠습니다.',
    bank_transfer_description: '신청해주셔서 감사합니다.',
    depositor: '예금주',
    bank: '은행명',
    account_number: '계좌번호',
    deposit_amount: '입금 금액',
    lesson_information: '강의정보',
    account_transfer: '계좌이체',
    credit_card: '신용카드',
    payment_method: '결제 수단',
    payment_information: '결제 정보',
    lesson_price: '수강권 금액',
    input_name_message: '이름을 입력해 주세요',
    total_amount: '총 결제 금액',
    seller_information: '판매자 정보',
    refund_information: '환불 안내',
    business_registration_number: '사업자번호',
    business_name: '사업자명',
    e_commerce_registration_number: '통신판매업 신고번호',
    representative: '대표자명',
    one_ticket: '1회 수업권',
    education_office_registration_number: '교육청 등록번호',
    business_address: '사업자소재지',
    lesson_refund_message_1: '수강료 환불은 학원의 설립 및 과외교습에 관한 법률 시행령 제18조 제3항 별표 4에 의거 진행됩니다.',
    lesson_refund_message_2: '다만, 입점사별로 환불정책이 다를 경우 입점사의 환불 정책에 따라 환불이 진행됩니다.',
    lesson_refund_message_3: '본 주문 내용 및 약관 내용을 확인하였으며, 예약에 동의합니다.',
    lesson_refund_message_4: '로우그래피(주)는 통신판매중개자이며, 통신판매의 당사자가 아닙니다.',
    lesson_refund_message_5: '상품, 상품 정보, 거래, 이용에 관한 의무와 책임은 판매자에게 있습니다.',
    studio_announcement: '스튜디오 공지사항',
    language_setting: '언어 설정',
    no_lessons: '등록된 수업이 없습니다',
    purchase_pass: '패스권 구매하기',
    change_locale_dialog_title: '언어 변경',
    change_locale_dialog_message: `언어 변경 후 앱을 재시작하시겠습니까?`,
  },
  en: {
    welcome: "Welcome!",
    login: "Login",
    kakao_login: "Continue with Kakao",
    apple_login: "Continue with Apple",
    email_login: "Continue with Email",
    google_login: "Continue with Google",
    email: "Email",
    password: "Password",
    input_email_message: "Please enter your email",
    input_password_message: "Please enter your password",
    not_member_sign_up: "Not a member yet?",
    create_account: "Sign Up",
    do_start: "Get Started",
    sign_up: "Sign Up",
    required: "Required",
    email_format: "Email format",
    password_min_length: "At least 8 characters",
    password_requirements: "Combination of letters, numbers, and special characters",
    next: "Next",
    fail_login: "Login Failed",
    fail_sign_up: "Sign-up Failed",
    unknown_error_message: "An unknown error occurred",
    onboarding_profile: "Profile Setup",
    onboarding_favorite_studio: "Favorite Studio",
    onboarding_agreement: "Privacy Agreement",
    change_profile_message: "Set up your profile!",
    change_profile_description: "You can change it anytime. Create your own nickname.",
    follow_studio_message: "Follow your favorite studio",
    follow_studio_description: "Which studio are you interested in?",
    agreement_message: "Please agree to continue!",
    all_agreement: "Agree to all",
    service_terms_agreement_required: "[Required] Terms of Service",
    service_privacy_agreement_required: "[Required] Privacy Policy",
    service_terms_agreement: "Terms of Service",
    service_privacy_agreement: "Privacy Policy",
    nick_name: "Nickname",
    welcome_title: "Welcome! 🎉",
    welcome_message: "Create amazing moments with Rawgraphy.",
    duplicate_nick_name_message: "This nickname is already in use",
    popular_studio: "Popular Studios",
    popular_lesson: "Popular Lessons",
    studio: "Studio",
    more: "More",
    following: "Following",
    follow: "Follow",
    ticket: "Lesson Ticket",
    payment_records: "Purchase History",
    terms_and_policy: "Terms & Policies",
    inquiry: "Contact Us",
    log_out_success_message: "Successfully logged out.",
    log_out_dialog_message: "Are you sure you want to log out?",
    log_out: "Log Out",
    rawgraphy: "Rawgraphy",
    under_development_message: "This menu is under development. Please wait a little longer!",
    sign_out: "Delete Account",
    account: "Account",
    payment: "Make Payment",
    app_version: "App Version",
    edit_profile: "Edit Profile",
    notification: "Notifications",
    notification_setting: "Notification Settings",
    upcoming_lessons: "Upcoming Lessons",
    sign_out_reason_no_contents: "Not enough content I want.",
    sign_out_reason_no_use: "I don't use the app often.",
    sign_out_reason_error: "Frequent errors while using the app.",
    sign_out_reason_new_account: "I want to create a new account.",
    sign_out_title: "Are you sure you want to leave? 😢",
    sign_out_description: "We're sad to see you go.\nIf you delete your account, your data and activity will be removed, but you can recover it within a month.",
    sign_out_reason_question: "We’d love to know why you’re leaving.",
    sign_out_dialog_message: "Are you sure you want to delete your account?\nAll your data will be erased.",
    guitar: "Guitar",
    continue_use: "Continue Using",
    do_sign_out: "Yes, Delete My Account",
    sign_out_reason_placeholder: "What was inconvenient? Leave feedback to help us improve!",
    maintenance_title: "Server Maintenance",
    maintenance_description: "The system is under maintenance for a better experience.",
    maintenance_try_later: "Please try again later.",
    maintenance_time: "Estimated Maintenance Time: 22:00 ~ 02:00",
    empty_notification_title: "No New Notifications",
    empty_notification_description: "You will see updates here when they arrive.",
    invalid_date_format: "Invalid Date",
    days_ago: "{n} days ago",
    hours_ago: "{n} hours ago",
    minutes_ago: "{n} minutes ago",
    minutes: "minutes",
    just_now: "Just now",
    my_ticket: "View My Lesson Ticket",
    purchase_ticket: "Purchase Lesson Ticket",
    finish_lesson_title: "Lesson Ended",
    date: "Date",
    day: "Day",
    mon: "MON",
    tue: "TUE",
    wed: "WED",
    thu: "THU",
    fri: "FRI",
    sat: "SAT",
    sun: "SUN",
    unknown: "",
    finish: "Finish",
    start: "Start",
    won: "KRW",
    lesson_duration: "Lesson Duration",
    lesson_room: "Lesson Room",
    bank_transfer_message: "Please transfer to the account below, and we will confirm your purchase.",
    bank_transfer_description: "Thank you for your request.",
    depositor: "Depositor",
    bank: "Bank",
    account_number: "Account Number",
    deposit_amount: "Deposit Amount",
    lesson_information: "Lesson Information",
    account_transfer: "Bank Transfer",
    confirm: 'Confirm',
    credit_card: "Credit Card",
    payment_method: "Payment Method",
    payment_information: "Payment Information",
    lesson_price: "Lesson Pass Price",
    input_name_message: "Please enter your name",
    total_amount: "Total Payment Amount",
    seller_information: "Seller Information",
    refund_information: "Refund Policy",
    business_registration_number: "Business Registration Number",
    business_name: "Business Name",
    e_commerce_registration_number: "E-commerce Registration Number",
    representative: "Representative",
    one_ticket: "One-time Lesson Pass",
    education_office_registration_number: "Education Office Registration Number",
    business_address: "Business Address",
    lesson_refund_message_1: "Refunds are processed in accordance with Article 18, Paragraph 3, Appendix 4 of the Enforcement Decree of the Act on the Establishment and Extracurricular Tutoring of Private Institutes.",
    lesson_refund_message_2: "However, if the refund policy differs by the vendor, refunds will be handled according to the vendor's refund policy.",
    lesson_refund_message_3: "I have reviewed the order details and terms and agree to the reservation.",
    lesson_refund_message_4: "Rawgraphy Inc. is an intermediary and not a direct seller.",
    lesson_refund_message_5: "The responsibility for products, product information, transactions, and usage lies with the seller.",
    studio_announcement: 'Studio Announcement',
    language_setting: "Language Setting",
    no_lessons: 'No registered lessons.',
    purchase_pass: 'Purchase Pass Ticket',
    change_locale_dialog_title: 'Selected Language',
    change_locale_dialog_message: `Would you like to change it and restart the app?`,
  }
};
