import type { Metadata } from "next";
import "./globals.css";
import { GetEventResponse } from "@/app/endpoint/event.endpoint";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body style={{backgroundColor: "white", color: "white"}}>
      {children}
    </body>
    </html>
  );
}

declare global {
  interface Window {
    KloudEvent: Record<string, (data?: string) => void>;
    push: (screen: string, data?: string) => void;
    replace: (screen: string, data?: string) => void;
    clearAndPush: (screen: string, data?: string) => void;
    back: () => void;
    rootNext: (screen: string) => void;
    navigateMain: (bootInfo: string) => void;
    setToken: (token: string) => void;
    sendBootInfo: (bootInfo: string) => void;
    onSplashStarted: () => void;
    showToast: (message: string) => void;
    sendHapticFeedback: () => void;
    sendAppleLogin: () => void;
    sendKakaoLogin: (configuration: string) => void;
    sendGoogleLogin: () => void;
    showDialog: (info: string) => void;
    showBottomDialog: (info: string) => void;
    requestPayment: (command: string) => void;

    onKakaoLoginSuccess: (data: { code: string }) => void;
    onAppleLoginSuccess: (data: { code: string }) => void;
    onGoogleLoginSuccess: (data: { code: string }) => void;
    onPaymentSuccess: (data: { transactionId: string, paymentId: string }) => void;
    onErrorInvoked: (data: {code: string}) => void;
    onDialogConfirm: (data: GetEventResponse) => void;
    onHideDialogConfirm: (data: {id: string, clicked: boolean}) => void;

  }
}